In [1]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2329, 3169, 1994, 5142],
 [2329, 3169, 1994, 1379],
 [2329, 9522, 1994, 6231],
 [7775, 3190, 1511, 9822, 4761],
 [7775, 3190, 1511, 9822, 879],
 [1985, 2329, 5457, 1994, 6740],
 [5523, 7614, 300, 9822]]

In [6]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2329 3169 1994 5142]
 [   0    0    0    0 2329 3169 1994 1379]
 [   0    0    0    0 2329 9522 1994 6231]
 [   0    0    0 7775 3190 1511 9822 4761]
 [   0    0    0 7775 3190 1511 9822  879]
 [   0    0    0 1985 2329 5457 1994 6740]
 [   0    0    0    0 5523 7614  300 9822]]


In [7]:
## feature representation
dim=10

In [8]:
model=Sequential([
    Input(shape=(sent_length,)),
    Embedding(voc_size,dim)
    ])
model.compile('adam','mse')

W0000 00:00:1751714572.080642   68586 gpu_device.cc:2341] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
output = model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


In [15]:
output

array([[[-3.2322682e-02, -2.2875046e-02,  2.2338342e-02,  2.7200792e-02,
          3.6824409e-02, -2.8243769e-02,  3.1952586e-02, -5.6695230e-03,
          3.6320303e-02,  2.9865753e-02],
        [-3.2322682e-02, -2.2875046e-02,  2.2338342e-02,  2.7200792e-02,
          3.6824409e-02, -2.8243769e-02,  3.1952586e-02, -5.6695230e-03,
          3.6320303e-02,  2.9865753e-02],
        [-3.2322682e-02, -2.2875046e-02,  2.2338342e-02,  2.7200792e-02,
          3.6824409e-02, -2.8243769e-02,  3.1952586e-02, -5.6695230e-03,
          3.6320303e-02,  2.9865753e-02],
        [-3.2322682e-02, -2.2875046e-02,  2.2338342e-02,  2.7200792e-02,
          3.6824409e-02, -2.8243769e-02,  3.1952586e-02, -5.6695230e-03,
          3.6320303e-02,  2.9865753e-02],
        [-1.5054740e-02, -4.9437992e-03,  3.8883574e-03,  2.6023928e-02,
         -4.2704869e-02, -7.6272264e-03,  3.7977282e-02,  3.7776235e-02,
          1.4799025e-02,  2.5410023e-02],
        [-1.0823239e-02,  2.1964882e-02,  3.3938181e-02, -3.

In [14]:
output.shape

(7, 8, 10)

In [12]:
single_input = np.expand_dims(embedded_docs[0], axis=0)
model.predict(single_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[[-0.03232268, -0.02287505,  0.02233834,  0.02720079,
          0.03682441, -0.02824377,  0.03195259, -0.00566952,
          0.0363203 ,  0.02986575],
        [-0.03232268, -0.02287505,  0.02233834,  0.02720079,
          0.03682441, -0.02824377,  0.03195259, -0.00566952,
          0.0363203 ,  0.02986575],
        [-0.03232268, -0.02287505,  0.02233834,  0.02720079,
          0.03682441, -0.02824377,  0.03195259, -0.00566952,
          0.0363203 ,  0.02986575],
        [-0.03232268, -0.02287505,  0.02233834,  0.02720079,
          0.03682441, -0.02824377,  0.03195259, -0.00566952,
          0.0363203 ,  0.02986575],
        [-0.01505474, -0.0049438 ,  0.00388836,  0.02602393,
         -0.04270487, -0.00762723,  0.03797728,  0.03777624,
          0.01479902,  0.02541002],
        [-0.01082324,  0.02196488,  0.03393818, -0.0359452 ,
         -0.01925959, -0.04721229, -0.04254163,  0.02855167,
         -0.03523625,  0.03382838],
        [ 0.04366044, -0.0306219 , -0.02424492, -0.0