In [18]:
from tensorflow.keras.preprocessing.text import one_hot

In [19]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [20]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9945, 4595, 9520, 5637],
 [9945, 4595, 9520, 7466],
 [9945, 1576, 9520, 2585],
 [5542, 9482, 2430, 9595, 2349],
 [5542, 9482, 2430, 9595, 103],
 [3666, 9945, 1890, 9520, 5377],
 [8469, 9462, 8256, 9595]]

In [23]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9945 4595 9520 5637]
 [   0    0    0    0 9945 4595 9520 7466]
 [   0    0    0    0 9945 1576 9520 2585]
 [   0    0    0 5542 9482 2430 9595 2349]
 [   0    0    0 5542 9482 2430 9595  103]
 [   0    0    0 3666 9945 1890 9520 5377]
 [   0    0    0    0 8469 9462 8256 9595]]


In [25]:
## feature representation
dim=10

In [26]:
model=Sequential([Embedding(voc_size,dim,input_length=sent_length)])
model.compile('adam','mse')

In [27]:
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

I0000 00:00:1751708417.655675   35836 service.cc:145] XLA service 0x7fd0f00030f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1751708417.655983   35836 service.cc:153]   StreamExecutor device (0): NVIDIA RTX A1000 Laptop GPU, Compute Capability 8.6
2025-07-05 09:40:17.759718: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8907


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 530ms/step


I0000 00:00:1751708417.893297   35836 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


array([[[ 0.02720622, -0.01585617,  0.00183653,  0.01804915,
         -0.00314492,  0.01331099,  0.01036093, -0.02515212,
          0.01550316, -0.03856158],
        [ 0.02720622, -0.01585617,  0.00183653,  0.01804915,
         -0.00314492,  0.01331099,  0.01036093, -0.02515212,
          0.01550316, -0.03856158],
        [ 0.02720622, -0.01585617,  0.00183653,  0.01804915,
         -0.00314492,  0.01331099,  0.01036093, -0.02515212,
          0.01550316, -0.03856158],
        [ 0.02720622, -0.01585617,  0.00183653,  0.01804915,
         -0.00314492,  0.01331099,  0.01036093, -0.02515212,
          0.01550316, -0.03856158],
        [-0.03455745, -0.03959769, -0.01531984,  0.03632206,
          0.00610788,  0.03522455,  0.0490389 , -0.00952028,
         -0.00111841, -0.03927686],
        [-0.0356742 , -0.02718365,  0.02719393, -0.04641856,
         -0.01155205,  0.04993559,  0.02330153,  0.03535512,
          0.04138366,  0.03489307],
        [ 0.00796139,  0.04091816, -0.02535726, -0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 9945, 4595, 9520, 5637], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

/home/harsh/GenAI/.venv/lib/python3.11/site-packages/keras/src/models/functional.py:241: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: keras_tensor_2
Received: inputs=('Tensor(shape=(8,))',)
  warnings.warn(msg)


ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("sequential_2_1/Cast:0", shape=(8,), dtype=float32). Expected shape (None, 8), but input has incompatible shape (8,)

Arguments received by Sequential.call():
  • inputs=('tf.Tensor(shape=(8,), dtype=int32)',)
  • training=False
  • mask=('None',)
  • kwargs=<class 'inspect._empty'>